
room: #Escritorio a ser monitorado
    id: 44 #ID da sala no sistema de agendamentos da RNP
    nodes: 2 #quantidade de nós da sala

node: #informações do nó
    node_id: 1
    distance_max: 10 #distancia em centímetros entre o sensor e o primeiro obstáculo fixo

topics:
      topic_scheduler: '/b2cdbbe033db11eb853de20166b6007e/relogio/attrs' #topico da aplicação relogio
      topic_raspberry: '/b2cdbbe033db11eb853de20166b6007e/raspberry/attrs' #topico para detecção de ausencia
      topic_heartbeat: '/b2cdbbe033db11eb853de20166b6007e/rasp_con/attrs' #topico do mecanismo de tolerancia a falhas
      
mqtt_broker: #IP e porta do mosquitto
      host: '200.143.200.6'
      port: 8002