
room: #Escritorio a ser monitorado
    id: 44 #ID da sala no sistema de agendamentos da RNP
    nodes: 2 #quantidade de nós da sala

email: #Configurações de email
      #Dados do remetente
      email_sender: 'escritoriointeligenternp@gmail.com'
      password_sender: 'R@spb3rry123.'
      #Dados do destinatario
      email_receiver: 'franciellysouza552@gmail.com'
      #Dados do email
      availability: #email informando de que a sala está disponível
            subject: 'Sala Disponível'
            message: 'O ambiente está disponível!'
      failure: #email informando que o nó x parou de funcionar
            subject: 'Falha no sensor'
            message: 'O nó não responde!'

topics:
      subscribe:
         topic_scheduler: '/admin/249eb4/config' #topico da aplicação relogio
         topic_raspberry: '/admin/17f28c/config' #topico para detecção de ausencia
         topic_heartbeat: '/admin/4f30e2/config' #topico do mecanismo de tolerancia a falhas
      publish:
         topic_scheduler: '/admin/249eb4/attrs'
         topic_raspberry: '/admin/17f28c/attrs'
         topic_heartbeat: '/admin/4f30e2/attrs'

mqtt_broker: #IP e porta do mosquitto
      host: 'localhost'
      port: 1883
