Nodes:
      - ID: 01
      - ID: 02
      - ID: 03

Email:
      Username_sender: 'escritoriointeligente123@gmail.com'
      Password_sender: 'fran123.'
      Username_recipient: 'franciellysouza552@gmail.com'
      Subject: 'Sala Disponivel'
      Message: 'Teste'

Topics:
      Subscribe:
         topic_scheduler: '/admin/249eb4/config'
         topic_raspberry: '/admin/17f28c/config'
         topic_is_alive: '/admin/4f30e2/config'
      Publish:
         topic_scheduler: '/admin/249eb4/attrs'
         topic_raspberry: '/admin/17f28c/attrs'
         topic_is_alive: '/admin/4f30e2/attrs'