Nodes:
      - ID: 01
      - ID: 02
      - ID: 03
      - ID: 04
      - ID: 05

Email:
      Username_sender: 'escritoriointeligente123@gmail.com'
      Password_sender: 'fran123.'
      Username_recipient: 'franciellysouza552@gmail.com'
      Subject: 'Sala Disponivel'
      Message: 'Teste'

Topics:
      topic_scheduler: '/admin/249eb4/attrs'
      topic_raspberry: '/admin/17f28c/config'