Nodes:
      - ID: 01
      - ID: 02
      - ID: 03

Email:
      Username_sender: 'escritoriointeligente123@gmail.com'
      Password_sender: 'fran123.'
      Username_recipient: 'franciellysouza552@gmail.com'
      Subject: 'Sala Disponivel'
      Message: 'Teste'

Topics:
      Subscribe:
         topic_scheduler: '/4jggokgpepnvsb2uv4s40d59ov/relogio01/attrs'
         topic_raspberry: '/4jggokgpepnvsb2uv4s40d59ov/raspberry/attrs'
         topic_is_alive: '/4jggokgpepnvsb2uv4s40d59ov/raspberry_controle/attrs'
      Publish:
         topic_scheduler: '/4jggokgpepnvsb2uv4s40d59ov/relogio01/attrs'
         topic_raspberry: '/4jggokgpepnvsb2uv4s40d59ov/raspberry/attrs'
         topic_is_alive: '/4jggokgpepnvsb2uv4s40d59ov/raspberry_controle/attrs'